using System.ComponentModel.DataAnnotations;
using Callu.Domain.Base;

namespace Callu.Domain.Entities;

/// <summary>
/// Represents an on-call schedule
/// </summary>
public class Schedule : BaseEntity
{

    /// <summary>
    /// Schedule name
    /// </summary>
    [Required]
    [StringLength(100)]
    public string Name { get; set; } = string.Empty;

    /// <summary>
    /// Schedule description
    /// </summary>
    [StringLength(500)]
    public string? Description { get; set; }

    /// <summary>
    /// Team ID this schedule belongs to
    /// </summary>
    public Guid TeamId { get; set; }

    /// <summary>
    /// Navigation property for team
    /// </summary>
    public virtual Team Team { get; set; } = null!;

    /// <summary>IANA timezone ID in which every rotation wall-clock time and DST resolution is evaluated.</summary>
    [StringLength(100)]
    public string Timezone { get; set; } = "UTC";

    /// <summary>Non-null while the stored occurrences are older than the schedule they expand; cleared by the materializer.</summary>
    public DateTime? NeedsRematerializeSince { get; set; }

    /// <summary>Rotation entries for this schedule.</summary>
    public virtual ICollection<ScheduleRotation> Rotations { get; set; } = new List<ScheduleRotation>();

    /// <summary>Materialized UTC occurrences generated by the ScheduleMaterializer.</summary>
    public virtual ICollection<ScheduleOccurrence> Occurrences { get; set; } = new List<ScheduleOccurrence>();
}
